### ISSUE TITLE
CryptoCertificateManager Error

### ISSUE THREAD

**Issue by kclinden** [vmware/o11n-plugin-crypto#5]
I am trying to use the CryptoCertificateManager.getHttpsCertificate() method, but I am getting a java.lang.NullPointerException with vRO 7.4 and the latest version of the plugin. Any known issues around this?

**Comment by kclinden** [comment]
Figured it out. I was trying to instantiate a new instance of CryptoCertificateManager, but you only need to call it. 
`var certs = CryptoCertificateManager.getHttpsCertificate("https://some-server.com");`

**Comment by dlinsley** [comment]
Added a note reflecting this behavior to the `CryptoCertificateManager Methods` wiki page.
